# 파일불러오기

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from apyori import apriori
import pickle
from tqdm import tqdm

In [18]:
df = pd.read_csv("./data/new_df_final.csv")
# store_data.csv
# df = pd.read_csv("./data/store_data.csv")
# df.head(2)

In [3]:
df = df.drop(["Unnamed: 0"], axis=1)

# 파일 복사

In [4]:
test = df.drop(["Unnamed: 0.1", "user_name", "food"], axis=1)

In [5]:
test

,galbigui,galchigui,godeungeogui,gopchanggui,dakgalbi,tteokgalbi,bulgogi,samgyeopsal,jangeogui,jogaegui,...,gamjatang,gomguk-seolleongtang,maeuntang,samgyetang,gochutwigim,saeutwigim,ojingeotwigim,yakgwa,hangwa,yukhoe
0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 데이터 형식 바꾸기

In [6]:
# 한줄씩 row 데이터를 뽑아서
foods = list()
cols  = test.columns
for i in tqdm(range( test.shape[0])):
    row_tmp = list()
    tmp = test.iloc[i, :]
    for j in range( tmp.shape[0]):
        # NaN이 아닌 컬럼만 획득
#         print(tmp[j])
        if tmp[j] == 1.0:
            row_tmp.append( cols[j] )
        else:
            row_tmp.append( np.nan )
#         # 그 컬럼명만 리스트에 담는다         
    foods.append( row_tmp )

100%|██████████| 78633/78633 [01:53<00:00, 694.31it/s]

In [7]:
test.shape[0]

78633

In [8]:
# len(foods) == test.shape[0]
len(foods)

78633

In [9]:
test.shape[1]

118

In [10]:
len(foods[0])

118

In [11]:
tmp_df = pd.DataFrame( foods )
tmp_df

,0,1,2,3,4,5,6,7,8,9,...,108,109,110,111,112,113,114,115,116,117
0,NaN,NaN,NaN,NaN,NaN,NaN,bulgogi,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,bulgogi,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,galbigui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,galbigui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,galbigui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 첫 번째 방법

In [12]:
tmp_df.shape

(78633, 118)

In [13]:
from tqdm import tqdm
records = []
for i in tqdm(range(78633)):
    records.append([str(tmp_df.values[i, j]) for j in range(0, 118)])

100%|██████████| 78633/78633 [00:58<00:00, 1345.66it/s]

In [14]:
len(records)

78633

In [15]:
association_rules   = apriori(records, min_support = 0.0045, min_confidence = .2, min_lift = 3, min_length = 2)
# Convert above rules into a list of rules
association_results = list(association_rules)

In [16]:
# Total number of rules generated
print(len(association_results))

8

In [95]:
for item in association_results:
    pair = item[0]
    items = [x for x in pair]
    print("Rule :"+ str(items[0]) + "->" + str(items[1]) )
    print("Support : {}".format(item[1]))
    print("Confidence : {}".format(item[2][0][2]))
    print("List : {}".format(ite m[2][0][3]))
    print("\n-------------------------------------------------\n")

Rule :doenjangjjigae->kimchijjigae
Support : 0.010809710935612275
Confidence : 0.24031665253039297
List : 6.756102730933998

-------------------------------------------------

Rule :yangnyeomchicken->friedchicken
Support : 0.03136087902025867
Confidence : 0.5452133539686049
List : 10.229482620523338

-------------------------------------------------

Rule :friedchicken->bulgogi
Support : 0.005010618951330866
Confidence : 0.5710144927536233
List : 10.713572562322991

-------------------------------------------------

Rule :doenjangjjigae->kimchijjigae
Support : 0.010809710935612275
Confidence : 0.24031665253039297
List : 6.756102730933998

-------------------------------------------------

Rule :yangnyeomchicken->friedchicken
Support : 0.03136087902025867
Confidence : 0.5452133539686049
List : 10.229482620523338

-------------------------------------------------

Rule :samgyeopsal->friedchicken
Support : 0.004819859346584767
Confidence : 0.6233552631578947
List : 11.69560830539125

-------------------------------------------------

Rule :friedchicken->bulgogi
Support : 0.005010618951330866
Confidence : 0.5710144927536233
List : 10.713572562322991

-------------------------------------------------

Rule :samgyeopsal->friedchicken
Support : 0.004819859346584767
Confidence : 0.6233552631578947
List : 11.69560830539125

-------------------------------------------------

# 함수 만들기 - 1차

- 로직
    1. 이미지 분석에서 나온 결과물인 음식이름(텍스트)를 받는다
    2. 만들어 놓은 규칙 데이터 프레임에서 그 음식이 있는 행을 찾는다
    3. 그 행에서 리프트가 가장 높은 음식을 선택한다
    4. 화면에 그것을 보내준단
    
- 참고자료
    1. https://bbiyakbbiyak.tistory.com/7

In [ ]:
def associ(food_text):
    food_output = select rule from rule_statics where rule = food_text and where max(lift)
    return food_output

# 함수 만들기 - 2차

In [ ]:
@csrf_exempt  
def associ(food_text):
    if request.method == 'GET':
        ar = [ request.session['userid'] ]
        
        sql = 
        """
            SELECT RULE FROM RULE_STATICS
            WHERE RULE=food_text AND
            WHERE MAX(LIFT)
        """
        
        cursor.execute(sql, ar) 
        data = cursor.fetchone()   
        print(data)

        return render(request, 'member/edit.html', {"one":data})