In [54]:
import pandas as pd
all_sub_data = pd.read_csv('./data/all_sub_data.csv')
all_sub_data= df.fillna('')

In [58]:
type(eval(all_sub_data.head(1).menu[0]))

list

In [59]:
all_sub_data['menu'] = all_sub_data['menu'].apply(eval)

In [60]:
type(all_sub_data['menu'][0])

list

## tf에 값 없으면 res_menu 에 식당 메뉴 넣기

In [61]:
for idx, i in enumerate(all_sub_data['tf']):
    if all_sub_data['tf'][idx] == '' :
        all_sub_data['tf'][idx] = all_sub_data['menu'][idx]

/home/team/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [62]:
#체크
all_sub_data[all_sub_data['tf']=='']
#0 => 성공

Empty DataFrame
Columns: [user_name, res_name, review, menu, PN, spicy, sweet, sour, saulty, mild, normal, for_vegitarian, for_mania, for_starter, indirec_mentioned, direc_mentioned, res_menus, tf]
Index: []

## 안쓰는 행 버리기

In [24]:
# all_sub_data.drop(['indirec_mentioned','direc_mentioned','res_menus	'], axis=1, inplace=True)

In [63]:
type(all_sub_data['tf'][0])

str

In [66]:

    if type(all_sub_data['tf'][idx]) == str :
        all_sub_data['tf'][idx] = all_sub_data['tf'][idx].replace(',',' ') 
        all_sub_data['tf'][idx] = all_sub_data['tf'][idx].split(' ')

In [67]:
all_sub_data.head()

,user_name,res_name,review,menu,PN,spicy,sweet,sour,saulty,mild,normal,for_vegitarian,for_mania,for_starter,indirec_mentioned,direc_mentioned,res_menus,tf
0,KgQnRvsPSrJJTOCp-reYZA,Seoul Garden Korean Restaurant,we have been here three times now and have lov...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",0,1,0,0,1,0,0,1,1,1,0,0,0,"[, kkakdugi]"
1,1goJa-4OKwc--vlISRm54g,Seoul Garden Korean Restaurant,seoul garden was excellent we moved to this a...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",1,0,0,0,0,0,0,0,1,1,0,0,0,"[bulgogi, galbigui, kimchijjigae, doenjangjjig..."
2,6agrhhelmT9DLUfx4EeZVA,Seoul Garden Korean Restaurant,i like this place a lot one of the best korean...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",1,0,0,0,0,0,1,0,0,0,0,0,0,"[bulgogi, galbigui, kimchijjigae, doenjangjjig..."
3,AvaeN3hgxdytAEMlNud-FQ,Seoul Garden Korean Restaurant,korean barbecue at its finest the outside does...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",1,0,0,0,0,0,0,0,1,1,0,0,0,"[bulgogi, galbigui, kimchijjigae, doenjangjjig..."
4,wML8YiFzB1JuCfyhPptiSg,Seoul Garden Korean Restaurant,food was ok the food looks good in pictures bu...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",0,1,0,0,0,1,0,0,0,0,0,0,0,"[, gyeranfry]"

In [72]:
for idx in range(len(all_sub_data['tf'])) :
    if all_sub_data['tf'][idx][0] == '' :
            all_sub_data['tf'][idx] = all_sub_data['tf'][idx][1:]

/home/team/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [73]:
all_sub_data

,user_name,res_name,review,menu,PN,spicy,sweet,sour,saulty,mild,normal,for_vegitarian,for_mania,for_starter,indirec_mentioned,direc_mentioned,res_menus,tf
0,KgQnRvsPSrJJTOCp-reYZA,Seoul Garden Korean Restaurant,we have been here three times now and have lov...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",0,1,0,0,1,0,0,1,1,1,0,0,0,[kkakdugi]
1,1goJa-4OKwc--vlISRm54g,Seoul Garden Korean Restaurant,seoul garden was excellent we moved to this a...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",1,0,0,0,0,0,0,0,1,1,0,0,0,"[bulgogi, galbigui, kimchijjigae, doenjangjjig..."
2,6agrhhelmT9DLUfx4EeZVA,Seoul Garden Korean Restaurant,i like this place a lot one of the best korean...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",1,0,0,0,0,0,1,0,0,0,0,0,0,"[bulgogi, galbigui, kimchijjigae, doenjangjjig..."
3,AvaeN3hgxdytAEMlNud-FQ,Seoul Garden Korean Restaurant,korean barbecue at its finest the outside does...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",1,0,0,0,0,0,0,0,1,1,0,0,0,"[bulgogi, galbigui, kimchijjigae, doenjangjjig..."
4,wML8YiFzB1JuCfyhPptiSg,Seoul Garden Korean Restaurant,food was ok the food looks good in pictures bu...,"[bulgogi, galbigui, kimchijjigae, doenjangjjig...",0,1,0,0,0,1,0,0,0,0,0,0,0,[gyeranfry]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110908,MrsOS2014,Sam Sam Korean Fried Chicken,only veggie dishes on menu vegetable noodles...,"[friedchicken, yangnyeomchicken]",0,1,0,0,1,0,0,1,0,0,0,0,0,[dubujorim]
110909,Alison A,Sam Sam Korean Fried Chicken,we enjoyed ourselves so much we returned the n...,"[friedchicken, yangnyeomchicken]",1,1,1,0,0,0,0,0,1,0,0,0,0,"[friedchicken, yangnyeomchicken]"
110910,addiction4travel,Sam Sam Korean Fried Chicken,went with a couple of friends for dinner chick...,"[friedchicken, yangnyeomchicken]",0,0,0,0,0,0,0,0,1,0,0,0,0,[baechukimchi]
110911,152JoyB,Sam Sam Korean Fried Chicken,we both enjoyed our meal at this restaurant an...,"[friedchicken, yangnyeomchicken]",1,0,0,0,0,0,0,0,1,1,0,0,0,"[friedchicken, yangnyeomchicken]"
110912,LC888,Sam Sam Korean Fried Chicken,the place was busy doesnt take reservation and...,"[friedchicken, yangnyeomchicken]",0,0,0,0,1,0,0,0,1,0,0,0,0,"[friedchicken, friedchicken]"

In [75]:
all_sub_data.to_csv('./data/all_sub_data_all_list.csv',index=False)