# 음식 리스트 업로드

In [1]:
food_in_english =[
    'galbigui',
 'galchigui' ,
 'godeungeogui',
 'gopchanggui',
 'dakgalbi',
 'deodeokgui',
 'tteokgalbi',
 'bulgogi',
 'samgyeopsal',
 'jangeogui',
 'jogaegui',
 'jogigui',
 'hwangtaegui',
 'hunjeori',
 'gyelangug',
 'tteokguk-mandutguk',
 'muguk',
 'miyeokguk',
 'bugeotguk',
 'siraegiguk',
 'yukgaejang',
 'kongnamulguk',
 'gwamegi',
 'yangnyeomchicken',
 'jeotgal',
 'kongjaban',
 'pyeonyuk',
 'pizza',
 'friedchicken',
 'gatkimchi',
 'kkakdugi',
 'nabakkimchi',
 'musaengchae',
 'baechukimchi',
 'baekkimchi',
 'buchukimchi',
 'yeolmukimchi',
 'oisobagi',
 'chonggakkimchi',
 'pakimchi',
 'gajibokkeum',
 'gosarinamul',
 'miyeokjulgibokkeum',
 'sukjunamul',
 'sigeumchinamul',
 'aehobakbokkeum',
 'gyeongdan',
 'kkultteok',
 'songpyeon',
 'mandu',
 'ramyeon',
 'makguksu',
 'mulnaengmyeon',
 'bibimnaengmyeon',
 'sujebi',
 'yeolmuguksu',
 'janchiguksu',
 'jajangmyeon',
 'jjamppong',
 'jjolmyeon',
 'kalguksu',
 'kongguksu',
 'kkwaligochumuchim',
 'dorajimuchim',
 'dotorimuk',
 'japchae',
 'kongnamulmuchim',
 'hongeomuchim',
 'hoemuchim',
 'gimbap',
 'kimchibokkeumbap',
 'nurungji',
 'bibimbap',
 'saeubokkeumbap',
 'albap',
 'yubuchobap',
 'japgokbap',
 'jumeokbap',
 'gamjachaebokkeum',
 'geonsaeubokkeum',
 'gochujangjinmichaebokkeum',
 'dubukimchi',
 'tteokbokki',
 'rabokki',
 'myeolchibokkeum',
 'sausagebokkeum',
 'eomukbokkeum',
 'ojingeochaebokkeum',
 'jeyukbokkeum',
 'jukkumibokkeum',
 'bossam',
 'sujeonggwa',
 'sikhye',
 'ganjanggejang',
 'yangnyeomgejang',
 'kkaesipjangajji',
 'tteokkkochi',
 'gamjajeon',
 'gyeranmari',
 'gyeranfry',
 'kimchijeon',
 'dongeurangttaeng',
 'saengseonjeon',
 'pajeon',
 'hobakjeon',
 'gopchangjeongol',
 'galchijorim',
 'gamjajorim',
 'godeungeojorim',
 'kkongchijorim',
 'dubujorim',
 'ttangkongjorim',
 'mechurialjangjorim',
 'yeongeunjorim',
 'ueongjorim',
 'jangjorim',
 'kodarijorim',
 'jeonbokjuk',
 'hobakjuk',
 'kimchijjigae',
 'dakgyejang',
 'dongtaejjigae',
 'doenjangjjigae',
 'sundubujjigae',
 'galbijjim',
 'gyeranjjim',
 'kimchijjim',
 'kkomakjjim',
 'dakbokkeumtang',
 'suyuk',
 'sundae',
 'jokbal',
 'jjimdak',
 'haemuljjim',
 'galbitang',
 'gamjatang',
 'gomguk-seolleongtang',
 'maeuntang',
 'samgyetang',
 'chueotang',
 'gochutwigim',
 'saeutwigim',
 'ojingeotwigim',
 'yakgwa',
 'yaksik',
 'hangwa',
 'meongge',
 'sannakji',
 'mulhoe',
 'yukhoe']

In [ ]:
# 제일 먼저 준 csv 파일 로드 
1. '리뷰'컬럼에 위 리스트의 오타o,오타x 인자 둘 중 하나라도 있으면 
=> 'direc_mentioned' 컬럼 값에 해당 음식 이름을 넣는다

In [2]:
# 오타 잡는 함수
def che(str1, str2):    
    st1 = list(0 for i in range(27))
    st2 = list(0 for j in range(27))
    str1=str1.strip()
    str2=str2.strip()
    if len(st1)>=len(st2):
        ss=len(st1)
    else:
        ss=len(st2)
    # print(ss)
    for i in str1:
        if ord(i)==32:
            st1[-1]+=1
        else:
            st1[ord(i)-97]+=1

    # print(st1)
    for i in str2:
        if ord(i)==32:
            st2[-1]+=1
        else:
            st2[ord(i)-97]+=1
    # print(st2)
    cnt = 0
    le=0
    for i in range(len(st1)):
        if st1[i]==st2[i]:
            cnt+=1
    if (cnt/ss) >=0.95:
        # print(cnt/ss)
        return 1
    else:
        # print(cnt/ss)
        return 0

# 파일 로드

## food_in_english에 적힌 음식 있는지 확인

In [ ]:
import pandas as pd

In [ ]:
rv = pd.read_csv('/home/team1/바탕화면/20200608_jinjaru1.csv')

In [ ]:
rv['tf']=''

In [ ]:
rv.head()

In [ ]:
len(rv)

In [ ]:
for i in range(len(rv)):
    for j in food_in_english:
        if j in rv['review'][i]:
            rv['tf'][i]+=','+j

In [ ]:
for j in rv.tf:
    print(j)

In [ ]:
rv.to_csv('/home/team1/바탕화면/just_foodname_in_dict.csv')

## 비슷한 단어 찾아서 있으면 넣기

In [ ]:
import pandas as pd
rv = pd.read_csv('./data/just_foodname_in_dict.csv')

In [ ]:
data=rv[:]

In [ ]:
data.head()

In [ ]:
import re
#data['review'] = data['review'][data['review'].str.match(r'[a-z ]', re.I)]
data['review'] = data['review'].str.replace(pat = r'[^a-zA-Z ]',repl=r'')

In [ ]:
data.head(20)

In [ ]:
! pip install tqdm

In [ ]:
# data.review.iloc[16694]

In [ ]:
import re
from tqdm import tqdm
error=list()
for i in tqdm(range(40001,80000)):
    print(i)
    for j in food_in_english:
        review = data['review'][i].split(' ')
        for k in review:
            try:
                if che(k.group(), j)==1:
                    data['tf'][i]+=','+j  
            except:
                error.append(k)

In [ ]:
data[40000:80000]
# okay

- 파일 저장

In [ ]:
data.to_csv('./data/just_foodname_in_dict_40000_80000.csv',index=False)

## 간접 언급 딕셔너리 선언

In [5]:
dic = {'kimchi pancakes': ['kimchijeon'],
 'kim chee pancake': ['kimchijeon'],
 'duk manduk gook': ['tteokguk-mandutguk'],
 'rice cake soup': ['tteokguk-mandutguk'],
 'duk manduk': ['tteokguk-mandutguk'],
 'mandu soup': ['tteokguk-mandutguk'],
 'tak bulgogi': ['dakgalbi'],
 'chicken bulgogi': ['dakgalbi'],
 'kimchi soup': ['kimchijjigae'],
 'kimchi stew': ['kimchijjigae'],
 'kimchi pork': ['kimchijjigae'],
 'jae yook': ['jeyukbokkeum'],
 'spicy pork': ['jeyukbokkeum'],
 'sweet potato noodles': ['japchae'],
 'cellophane noodles': ['japchae'],
 'gamjatang': ['gamjatang'],
 'pork bone soup': ['gamjatang'],
 'pork bone hotpot': ['gamjatang'],
 'pork bone spicy soup': ['gamjatang'],
 'soybean sprouts': ['kongnamulmuchim'],
 'bean sprouts': ['kongnamulmuchim'],
 'black bean noodles': ['jajangmyeon'],
 'zhazhamian': ['jajangmyeon'],
 'egg drop soup': ['gyelangug'],
 'spicy tofu': ['dubujorim'],
 'beef tartar dish': ['yukhoe'],
 'raw meat': ['yukhoe'],
 'kimchi ramen': ['ramyeon'],
 'ginseng soup': ['samgyetang'],
 'spring chicken inginseng': ['samgyetang'],
 'spicy chicken': ['yangnyeomchicken'],
 'buckwheat': ['makguksu'],
 'short rib soup': ['galbitang'],
 'marind sprouts': ['sukjunamul'],
 'korean sushi': ['gimbap'],
 'soft tofu soup': ['sundubujjigae'],
 'tofu soup': ['sundubujjigae'],
 'spicy tofu soup': ['sundubujjigae'],
 'dubu jigae': ['sundubujjigae'],
 'sea tofu': ['sundubujjigae'],
 'soft tofu stew': ['sundubujjigae'],
 'cucumber kimchi': ['oisobagi'],
 'spicy cucumbers': ['oisobagi'],
 'blood sausage': ['sundae'],
 'korean sausage': ['sundae'],
 'spicy rice cakes': ['tteokbokki'],
 'knife noodles': ['kalguksu'],
 'sweet rice drink': ['sikhye'],
 'soybean paste tofu soup': ['doenjangjjigae'],
 'miso soup': ['doenjangjjigae'],
 'daikon cube': ['kkakdugi'],
 'banchan': ['kkakdugi',
  'baechukimchi',
  'oisobagi',
  'gajibokkeum',
  'miyeokjulgibokkeum',
  'gosarinamul',
  'sukjunamul',
  'sigeumchinamul',
  'aehobakbokkeum',
  'japchae',
  'kongnamulmuchim',
  'gamjachaebokkeum',
  'myeolchibokkeum',
  'gyeranmari',
  'yeongeunjorim',
  'mechurialjangjorim',
  'dubujorim',
  'tteokbokki'],
 'side dish': ['kkakdugi',
  'baechukimchi',
  'oisobagi',
  'gajibokkeum',
  'miyeokjulgibokkeum',
  'gosarinamul',
  'sukjunamul',
  'sigeumchinamul',
  'aehobakbokkeum',
  'japchae',
  'kongnamulmuchim',
  'gamjachaebokkeum',
  'myeolchibokkeum',
  'gyeranmari',
  'yeongeunjorim',
  'mechurialjangjorim',
  'dubujorim',
  'tteokbokki'],
 'friedchicken': ['friedchicken'],
 'kimchi': ['baechukimchi'],
 'dumpling': ['mandu'],
 'pancake': ['gamjajeon', 'kimchijeon', 'pajeon'],
 'bbq': ['galbigui', 'samgyeopsal'],
 'barbeque': ['galbigui', 'samgyeopsal'],
 'meat': ['galbigui', 'samgyeopsal'],
 'seaweed': ['miyeokguk', 'miyeokjulgibokkeum'],
 'egg': ['gyeranfry', 'gyeranjjim'],
 'bulgogi chicken': ['dakgalbi'],
 'chicken bulgogi':['dakgalbi'],
 'daikon kimchi': ['kkakdugi'],
 'jaja meoung': ['jajangmyeon'],
 'black bean paste noodles': ['jajangmyeon'],
 'instant noodles': ['ramyeon'],
 'spicy pork tofu soup': ['kimchijjigae'],
 'soybean stew': ['doenjangjjigae'],
 'rice cakes': ['tteokbokki'],
 'sea noodle soup': ['jjamppong'],
 'spicy sea soup': ['jjamppong'],
 'potato sides': ['gamjajorim'],
 'potato dish': ['gamjajorim'],
 'korean style sushi': ['gimbap'],
 'haemool pajun': ['pajeon'],
 'potato pancakes': ['gamjajeon'],
 'bunsik': ['tteokbokki', 'gimbap'],
 'dduck mandoo soup': ['tteokguk-mandutguk']}

# 파일 로드 
    40000~80000

In [6]:
import pandas as pd
sub_data = pd.read_csv('./data/just_foodname_in_dict_40000_80000.csv')
sub_data = sub_data[40000:80000]

In [7]:
type(sub_data['tf'][40002])

float

In [8]:
sub_data

,Unnamed: 0,user_name,res_name,review,menu,PN,spicy,sweet,sour,saulty,mild,normal,for_vegitarian,for_mania,for_starter,indirec_mentioned,direc_mentioned,res_menus,tf
40000,40000,mwi6OSsC4fdTc7E-LHc0SQ,Bi Bim Bap,came here on a thursday night at around pm wit...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,0,0,1,0,1,0,0,1,0,0,0,0,",bibimbap"
40001,40001,LgJb17Bz9DbcbVpjlcqN2Q,Bi Bim Bap,when it comes to korean food i always enjoy th...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,1,0,0,0,0,0,1,1,1,0,0,0,",bulgogi,bibimbap"
40002,40002,AOBjDPZNOpDvrNIDEgri_Q,Bi Bim Bap,my favourite place for glutenfree bi bim bap t...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",1,0,0,0,0,0,0,0,1,0,0,0,0,NaN
40003,40003,ZO9NqSrsiHkAVqnU3hOc5g,Bi Bim Bap,great food and service hidden little gem had...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",1,0,0,0,0,0,1,0,0,0,0,0,0,NaN
40004,40004,zJH5RdZsRKOMtx3W0-Ba2Q,Bi Bim Bap,bi bam bap as the name suggests serves up a va...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,0,0,0,0,0,0,1,0,1,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,79995,evelynode,Don's Bogam BBQ & Wine Bar,we came here about pm on a weekday evening wit...,"['ojingeochaebokkeum', 'galbigui']",0,0,0,0,0,0,0,0,1,1,0,0,0,",bibimbap"
79996,79996,johnnycakes,Don's Bogam BBQ & Wine Bar,there are lots of variable reviews on this mid...,"['ojingeochaebokkeum', 'galbigui']",0,0,0,1,0,0,0,0,1,1,0,0,0,NaN
79997,79997,langsix,Don's Bogam BBQ & Wine Bar,my husband son and i did not have a reservatio...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,0,0,1,0,0,0,0,",bibimbap"
79998,79998,Arquimedes O,Don's Bogam BBQ & Wine Bar,we had a great expectation and it was a decept...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,0,0,1,1,0,0,0,NaN
79999,79999,Pamsreview,Don's Bogam BBQ & Wine Bar,we dined here on a sunday night early and the ...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,1,0,0,0,0,0,0,NaN

In [ ]:
# for i in dic.keys():
#     print(len(i.split(' ')))

## 오타 잡기

In [9]:
sub_data = sub_data.fillna('')

In [ ]:
# dic['spicy tofu']

In [10]:
for idx, i in enumerate(sub_data['review']):
    review = i.split(' ')
    idx = idx+40000
    for j in dic.keys():
        a = len(j.split(' '))
        for k in range(0, len(review)-a,1):
#             print(review[k:k+a])
            if che(review[k]+' '+review[k+1], j)==1:
                for x in dic[j] :
                    sub_data['tf'][idx] += ','+x
            #break
        #break
    #break
#         else:
#             for k in review:
#                 if che(k, j)==1:
#                     sub_data['tf'][idx]+=j

/home/team/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [11]:
sub_data

,Unnamed: 0,user_name,res_name,review,menu,PN,spicy,sweet,sour,saulty,mild,normal,for_vegitarian,for_mania,for_starter,indirec_mentioned,direc_mentioned,res_menus,tf
40000,40000,mwi6OSsC4fdTc7E-LHc0SQ,Bi Bim Bap,came here on a thursday night at around pm wit...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,0,0,1,0,1,0,0,1,0,0,0,0,",bibimbap,doenjangjjigae,kkakdugi,baechukimchi..."
40001,40001,LgJb17Bz9DbcbVpjlcqN2Q,Bi Bim Bap,when it comes to korean food i always enjoy th...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,1,0,0,0,0,0,1,1,1,0,0,0,",bulgogi,bibimbap,doenjangjjigae"
40002,40002,AOBjDPZNOpDvrNIDEgri_Q,Bi Bim Bap,my favourite place for glutenfree bi bim bap t...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",1,0,0,0,0,0,0,0,1,0,0,0,0,",baechukimchi"
40003,40003,ZO9NqSrsiHkAVqnU3hOc5g,Bi Bim Bap,great food and service hidden little gem had...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",1,0,0,0,0,0,1,0,0,0,0,0,0,
40004,40004,zJH5RdZsRKOMtx3W0-Ba2Q,Bi Bim Bap,bi bam bap as the name suggests serves up a va...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,0,0,0,0,0,0,1,0,1,0,0,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,79995,evelynode,Don's Bogam BBQ & Wine Bar,we came here about pm on a weekday evening wit...,"['ojingeochaebokkeum', 'galbigui']",0,0,0,0,0,0,0,0,1,1,0,0,0,",bibimbap,doenjangjjigae"
79996,79996,johnnycakes,Don's Bogam BBQ & Wine Bar,there are lots of variable reviews on this mid...,"['ojingeochaebokkeum', 'galbigui']",0,0,0,1,0,0,0,0,1,1,0,0,0,
79997,79997,langsix,Don's Bogam BBQ & Wine Bar,my husband son and i did not have a reservatio...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,0,0,1,0,0,0,0,",bibimbap"
79998,79998,Arquimedes O,Don's Bogam BBQ & Wine Bar,we had a great expectation and it was a decept...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,0,0,1,1,0,0,0,
79999,79999,Pamsreview,Don's Bogam BBQ & Wine Bar,we dined here on a sunday night early and the ...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,1,0,0,0,0,0,0,

In [12]:
sub_data.to_csv('./data/sub_data_40000_80000.csv', index=False)

In [ ]:
a=['a']
b=['b']
a+b

- 0~40000

In [ ]:
import pandas as pd
rv1 = pd.read_csv('./data/just_foodname_in_dict.csv')

In [ ]:
data1=rv1[:]

In [ ]:
import re
#data['review'] = data['review'][data['review'].str.match(r'[a-z ]', re.I)]
data1['review'] = data1['review'].str.replace(pat = r'[^a-zA-Z ]',repl=r'')

In [ ]:
import re
from tqdm import tqdm
error=list()
for i in tqdm(range(40000)):
    print(i)
    for j in food_in_english:
        review = data1['review'][i].split(' ')
        for k in review:
            try:
                if che(k.group(), j)==1:
                    data1['tf'][i]+=','+j  
            except:
                error.append(k)

In [ ]:
data1[:40000]

- 저장

In [ ]:
data1.to_csv('./data/just_foodname_in_dict_0_40000.csv',index=False)

# 파일 로드

In [19]:
sub_data1 = pd.read_csv('./data/just_foodname_in_dict_0_40000.csv')
sub_data1 = sub_data1[:40000]

In [24]:
sub_data1 = sub_data1.fillna('')
sub_data1

,Unnamed: 0,user_name,res_name,review,menu,PN,spicy,sweet,sour,saulty,mild,normal,for_vegitarian,for_mania,for_starter,indirec_mentioned,direc_mentioned,res_menus,tf
0,0,KgQnRvsPSrJJTOCp-reYZA,Seoul Garden Korean Restaurant,we have been here three times now and have lov...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",0,1,0,0,1,0,0,1,1,1,0,0,0,
1,1,1goJa-4OKwc--vlISRm54g,Seoul Garden Korean Restaurant,seoul garden was excellent we moved to this a...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",1,0,0,0,0,0,0,0,1,1,0,0,0,
2,2,6agrhhelmT9DLUfx4EeZVA,Seoul Garden Korean Restaurant,i like this place a lot one of the best korean...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",1,0,0,0,0,0,1,0,0,0,0,0,0,
3,3,AvaeN3hgxdytAEMlNud-FQ,Seoul Garden Korean Restaurant,korean barbecue at its finest the outside does...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",1,0,0,0,0,0,0,0,1,1,0,0,0,
4,4,wML8YiFzB1JuCfyhPptiSg,Seoul Garden Korean Restaurant,food was ok the food looks good in pictures bu...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",0,1,0,0,0,1,0,0,0,0,0,0,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,39995,DCcweTztEpGjZrtHhCWMcQ,Bi Bim Bap,i got the beef and mushroom stone bowl portio...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,0,0,0,0,0,0,0,1,1,0,0,0,
39996,39996,de-LBG2-d_OWYcGO0rfDTQ,Bi Bim Bap,a really yummy meal got the double chicken on ...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",1,1,0,0,0,1,0,0,1,1,0,0,0,
39997,39997,8d47j-gTl3BPqTBIhJGAXA,Bi Bim Bap,i tried bi bim baps new little italy location ...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,1,1,0,0,0,0,0,1,1,0,0,0,
39998,39998,v5ukvh_pZwOOAqPWFriC-Q,Bi Bim Bap,we ran into this place randomly while waiting ...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,1,0,1,0,0,0,0,1,0,0,0,0,",bibimbap"
39999,39999,r_ZVAjB8t4OFpL3DNihCXA,Bi Bim Bap,got beef and mushroom stone bowl takeout from ...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,0,0,0,0,0,1,0,0,0,0,0,0,

In [25]:
# 리뷰에 float 타입이 있어 오류가 났다 - Null 값 체크 
# sub_data1.isnull().sum()

Unnamed: 0           0
user_name            0
res_name             0
review               0
menu                 0
PN                   0
spicy                0
sweet                0
sour                 0
saulty               0
mild                 0
normal               0
for_vegitarian       0
for_mania            0
for_starter          0
indirec_mentioned    0
direc_mentioned      0
res_menus            0
tf                   0
dtype: int64

In [26]:
for idx, i in enumerate(sub_data1['review']):
    review = i.split(' ')
    idx = idx
    for j in dic.keys():
        a = len(j.split(' '))
        for k in range(0, len(review)-a,1):
#             print(review[k:k+a])
            if che(review[k]+' '+review[k+1], j)==1:
                for x in dic[j] :
                    sub_data1['tf'][idx] += ','+x

/home/team/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [27]:
sub_data1

,Unnamed: 0,user_name,res_name,review,menu,PN,spicy,sweet,sour,saulty,mild,normal,for_vegitarian,for_mania,for_starter,indirec_mentioned,direc_mentioned,res_menus,tf
0,0,KgQnRvsPSrJJTOCp-reYZA,Seoul Garden Korean Restaurant,we have been here three times now and have lov...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",0,1,0,0,1,0,0,1,1,1,0,0,0,
1,1,1goJa-4OKwc--vlISRm54g,Seoul Garden Korean Restaurant,seoul garden was excellent we moved to this a...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",1,0,0,0,0,0,0,0,1,1,0,0,0,
2,2,6agrhhelmT9DLUfx4EeZVA,Seoul Garden Korean Restaurant,i like this place a lot one of the best korean...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",1,0,0,0,0,0,1,0,0,0,0,0,0,
3,3,AvaeN3hgxdytAEMlNud-FQ,Seoul Garden Korean Restaurant,korean barbecue at its finest the outside does...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",1,0,0,0,0,0,0,0,1,1,0,0,0,
4,4,wML8YiFzB1JuCfyhPptiSg,Seoul Garden Korean Restaurant,food was ok the food looks good in pictures bu...,"['bulgogi', 'galbigui', 'kimchijjigae', 'doenj...",0,1,0,0,0,1,0,0,0,0,0,0,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,39995,DCcweTztEpGjZrtHhCWMcQ,Bi Bim Bap,i got the beef and mushroom stone bowl portio...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,0,0,0,0,0,0,0,1,1,0,0,0,",doenjangjjigae"
39996,39996,de-LBG2-d_OWYcGO0rfDTQ,Bi Bim Bap,a really yummy meal got the double chicken on ...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",1,1,0,0,0,1,0,0,1,1,0,0,0,
39997,39997,8d47j-gTl3BPqTBIhJGAXA,Bi Bim Bap,i tried bi bim baps new little italy location ...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,1,1,0,0,0,0,0,1,1,0,0,0,",yangnyeomchicken,doenjangjjigae"
39998,39998,v5ukvh_pZwOOAqPWFriC-Q,Bi Bim Bap,we ran into this place randomly while waiting ...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,1,0,1,0,0,0,0,1,0,0,0,0,",bibimbap"
39999,39999,r_ZVAjB8t4OFpL3DNihCXA,Bi Bim Bap,got beef and mushroom stone bowl takeout from ...,"['galbigui', 'bibimbap', 'gyeranfry', 'sigeumc...",0,0,0,0,0,0,1,0,0,0,0,0,0,

In [28]:
sub_data1.to_csv('./data/sub_data_0_40000.csv', index=False)

In [ ]:
sub_data1.head()

- 80000~끝

In [ ]:
import pandas as pd
rv2 = pd.read_csv('./data/just_foodname_in_dict.csv')

In [ ]:
data2=rv2
data2

In [ ]:
import re
#data['review'] = data['review'][data['review'].str.match(r'[a-z ]', re.I)]
data2['review'] = data2['review'].str.replace(pat = r'[^a-zA-Z ]',repl=r'')

In [ ]:
# data2['review'][0]

In [ ]:
import re
from tqdm import tqdm
error=list()
for i in tqdm(range(80000,len(data2['review']),1)):
    print(i)
    for j in food_in_english:
        review = data2['review'][i].split(' ')
        for k in review:
            try:
                if che(k.group(), j)==1:
                    data2['tf'][i]+=','+j  
            except:
                error.append(k)

In [ ]:
data2[80000:]

- 파일 저장

In [ ]:
data2.to_csv('./data/just_foodname_in_dict_80000_end.csv',index=False)

# 파일 로드

In [29]:
sub_data2 = pd.read_csv('./data/just_foodname_in_dict_80000_end.csv')
sub_data2 = sub_data2[80000:]

In [30]:
sub_data2['tf'] = sub_data2['tf'].fillna('')

In [31]:
sub_data2

,Unnamed: 0,user_name,res_name,review,menu,PN,spicy,sweet,sour,saulty,mild,normal,for_vegitarian,for_mania,for_starter,indirec_mentioned,direc_mentioned,res_menus,tf
80000,80000,HermanG170,Don's Bogam BBQ & Wine Bar,we went there for dinner packed and the reserv...,"['ojingeochaebokkeum', 'galbigui']",0,0,0,0,0,0,1,0,0,0,0,0,0,
80001,80001,sdias525_11,Don's Bogam BBQ & Wine Bar,the quality of the meats was excellent and the...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,0,0,1,1,0,0,0,
80002,80002,pjr1689,Don's Bogam BBQ & Wine Bar,we went on a thursday night and were able to g...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,1,0,0,0,0,0,0,
80003,80003,realdesertfox,Don's Bogam BBQ & Wine Bar,marinated rib eye steak was tasty and tender q...,"['ojingeochaebokkeum', 'galbigui']",1,1,0,0,0,0,0,1,1,1,0,0,0,
80004,80004,359julief,Don's Bogam BBQ & Wine Bar,barbecue tables were full but i had the best b...,"['ojingeochaebokkeum', 'galbigui']",0,0,0,0,0,0,0,1,0,0,0,0,0,",bibimbap"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110908,110908,MrsOS2014,Sam Sam Korean Fried Chicken,only veggie dishes on menu vegetable noodles...,"['friedchicken', 'yangnyeomchicken']",0,1,0,0,1,0,0,1,0,0,0,0,0,
110909,110909,Alison A,Sam Sam Korean Fried Chicken,we enjoyed ourselves so much we returned the n...,"['friedchicken', 'yangnyeomchicken']",1,1,1,0,0,0,0,0,1,0,0,0,0,
110910,110910,addiction4travel,Sam Sam Korean Fried Chicken,went with a couple of friends for dinner chick...,"['friedchicken', 'yangnyeomchicken']",0,0,0,0,0,0,0,0,1,0,0,0,0,
110911,110911,152JoyB,Sam Sam Korean Fried Chicken,we both enjoyed our meal at this restaurant an...,"['friedchicken', 'yangnyeomchicken']",1,0,0,0,0,0,0,0,1,1,0,0,0,
110912,110912,LC888,Sam Sam Korean Fried Chicken,the place was busy doesnt take reservation and...,"['friedchicken', 'yangnyeomchicken']",0,0,0,0,1,0,0,0,1,0,0,0,0,

In [32]:
for idx, i in enumerate(sub_data2['review']):
    review = i.split(' ')
    idx = idx+80000
    for j in dic.keys():
        a = len(j.split(' '))
        for k in range(0, len(review)-a,1):
#             print(review[k:k+a])
            if che(review[k]+' '+review[k+1], j)==1:
                for x in dic[j] :
                    sub_data2['tf'][idx] += ','+x

/home/team/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [33]:
sub_data2

,Unnamed: 0,user_name,res_name,review,menu,PN,spicy,sweet,sour,saulty,mild,normal,for_vegitarian,for_mania,for_starter,indirec_mentioned,direc_mentioned,res_menus,tf
80000,80000,HermanG170,Don's Bogam BBQ & Wine Bar,we went there for dinner packed and the reserv...,"['ojingeochaebokkeum', 'galbigui']",0,0,0,0,0,0,1,0,0,0,0,0,0,
80001,80001,sdias525_11,Don's Bogam BBQ & Wine Bar,the quality of the meats was excellent and the...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,0,0,1,1,0,0,0,
80002,80002,pjr1689,Don's Bogam BBQ & Wine Bar,we went on a thursday night and were able to g...,"['ojingeochaebokkeum', 'galbigui']",1,0,0,0,0,0,1,0,0,0,0,0,0,
80003,80003,realdesertfox,Don's Bogam BBQ & Wine Bar,marinated rib eye steak was tasty and tender q...,"['ojingeochaebokkeum', 'galbigui']",1,1,0,0,0,0,0,1,1,1,0,0,0,
80004,80004,359julief,Don's Bogam BBQ & Wine Bar,barbecue tables were full but i had the best b...,"['ojingeochaebokkeum', 'galbigui']",0,0,0,0,0,0,0,1,0,0,0,0,0,",bibimbap"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110908,110908,MrsOS2014,Sam Sam Korean Fried Chicken,only veggie dishes on menu vegetable noodles...,"['friedchicken', 'yangnyeomchicken']",0,1,0,0,1,0,0,1,0,0,0,0,0,",dubujorim"
110909,110909,Alison A,Sam Sam Korean Fried Chicken,we enjoyed ourselves so much we returned the n...,"['friedchicken', 'yangnyeomchicken']",1,1,1,0,0,0,0,0,1,0,0,0,0,
110910,110910,addiction4travel,Sam Sam Korean Fried Chicken,went with a couple of friends for dinner chick...,"['friedchicken', 'yangnyeomchicken']",0,0,0,0,0,0,0,0,1,0,0,0,0,
110911,110911,152JoyB,Sam Sam Korean Fried Chicken,we both enjoyed our meal at this restaurant an...,"['friedchicken', 'yangnyeomchicken']",1,0,0,0,0,0,0,0,1,1,0,0,0,
110912,110912,LC888,Sam Sam Korean Fried Chicken,the place was busy doesnt take reservation and...,"['friedchicken', 'yangnyeomchicken']",0,0,0,0,1,0,0,0,1,0,0,0,0,",friedchicken,friedchicken"

In [34]:
sub_data2.to_csv('./data/sub_data_80000_end.csv', index=False)